# **26-09-2026**

# **Numerical python**

## -> **NUMPY** stands for **Numerical python** main focused on numbers.

# -> In numpy there is only one collection i.e; **array**
# -> array can be **n-dimension**


In [89]:
import numpy as np

# **FEATURES OF ARRAY**
1. **Array is collection of homogeneous elements stored or arranged in continuous memory.**
2. **array is purly homogeneous datatype.**
3. **array is ordered datatype.**
4. **array supports duplicates.**
5. **array is faster than list.**
6. **array supports both positive and negative indexing.**
7. **it supports slicing.**
8. **array is partially mutable bcz only updation of element is possible not the insertion/deletion.**
9. **arry is fixed length.**
10. **array support element-wise operations.**
11. **array supports broadcasting.**

In [90]:
a1 = np.array([10,20,30,20])
print(a1)
print(type(a1))    # to check the type of data

[10 20 30 20]
<class 'numpy.ndarray'>


In [91]:
a1 = np.array([10,20,30,20,8.8])
print(a1)
print(type(a1))

[10.  20.  30.  20.   8.8]
<class 'numpy.ndarray'>


In [92]:
a1 = np.array([10,20,30,20,8+7j])
print(a1)
print(type(a1))

[10.+0.j 20.+0.j 30.+0.j 20.+0.j  8.+7.j]
<class 'numpy.ndarray'>


In [93]:
a1 = np.array([10,20,30,20,8.8,'numpy'])
print(a1)
print(type(a1))

['10' '20' '30' '20' '8.8' 'numpy']
<class 'numpy.ndarray'>


In [94]:
a1 = np.array([10,20,30,20,90])
print(a1[0])
print(a1[-1])
print(a1[::4])
print(a1[::-1])



10
90
[10 90]
[90 20 30 20 10]


# -> array is **partially mutable** bcz only updation of element is possible not the insertion/deletion, array is fixed length.

In [95]:
a1[4] = 100
print(a1)


[ 10  20  30  20 100]


# **Array Attributes**

In [96]:
a1 = np.array([10,20,30,20,100])
print(a1)
print(type(a1))

[ 10  20  30  20 100]
<class 'numpy.ndarray'>


In [97]:
print(a1.dtype) #datatype of array element

int64


In [98]:
print(a1.size) # number of elements present in array

5


In [99]:
print(a1.ndim) # dimension of the array(pair of square brackets indicates dimension)

1


In [100]:
print(a1.itemsize) # no_of_bytes of single element
print(a1.nbytes)  # no_of_bytes of all elements in array  -> single element takes 8 bytes here we have 5 elements so -> 5*8=40

8
40


In [101]:
print(type(a1.shape))  #type is tuple


<class 'tuple'>


# **28-09-2026**

# Types of array:
1. scalar array(zero-dimensional array) -> except list and tuple all types of datatype can support
2. 1D-array
3. 2D-array
4. multi-dimensional array

In [102]:
# SCALAR ARRAY
a0 = np.array(625)
print(a0)
print(a0.ndim)

625
0


In [103]:
a0 = np.array(9.87)
print(a0)
print(a0.ndim)

9.87
0


In [104]:
a0 = np.array(625+6j)
print(a0)
print(a0.ndim)

(625+6j)
0


In [105]:
a0 = np.array('a')
print(a0)
print(a0.ndim)

a
0


In [106]:
a0 = np.array(False)
print(a0)
print(a0.ndim)

False
0


# **to create array we use list[]**
# **no other collections are used to create array except list or tuple but mostly we use list[]**

In [107]:
# one-dimensional array
a1 = np.array([11,20,7,10,14])
print(a1)
print(a1.ndim)

print('-'*50)

a1 = np.array((11,20,7,10,14))
print(a1)
print(a1.ndim)

print('-'*50)

a1 = np.array({11,20,7,10,14})
print(a1)
print(a1.ndim)
# print(type(a1))

print('-'*50)

a1 = np.array({'id':1,'sub':'numpy'})
print(a1)
print(a1.ndim)
# print(type(a1))


[11 20  7 10 14]
1
--------------------------------------------------
[11 20  7 10 14]
1
--------------------------------------------------
{20, 7, 10, 11, 14}
0
--------------------------------------------------
{'id': 1, 'sub': 'numpy'}
0


In [108]:
# Two-dimensional array
a2 = np.array([ [1,2,3] , [12,11,13] ])
print(a2)
print(a2.ndim)

print(a2.shape)

[[ 1  2  3]
 [12 11 13]]
2
(2, 3)


# shape is an attribute which tells the no of elements in eah dimension

In [109]:
a3 = np.array([ [ [1,2] , [3,4] , [5,6] ] , 
                [ [7,8] , [9,10] , [11,12] ] ])
print(a3)
print(a3.ndim)
print(a3.shape) 


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [110]:
a1 = np.array([11,20,7])
print(a1)
print(a1.ndim)
print(a1.shape)

[11 20  7]
1
(3,)


# Broadcasting Rules:

shape : tuple

arr1 shape : (2,3,2)

arr2 shape : (2,3,2)

### **if you both the arrays are having same shape -> supports broadcasting**
-------------------------------------------------------------------------------
arr1 shape : (2,3,2)

arr2 shape : (2,1,2) # here 1 is like VIP number

### **if there is a differnt shape, mismatching only 1 is allowed ->  supports broadcasting**
-------------------------------------------------------------------------------
arr1 shape : (2,3,2)

arr2 shape :   (3,2)
# or
arr1 shape : (4,2,3,2)

arr2 shape :     (3,2)

### **if number of elements is mismatching then give the priority gives from right to left**

In [111]:
arr1 = np.array([2,4,6,2])
arr2 = np.array([5,3,1,2])

# 29-09-2026

## **ELEMENT-WISE OPERATIONS** -> b/w arrays of same shape

# 1.ARITHMATIC OPERATIONS

In [112]:
# ARITHMATIC OPERATIONS
print(arr1 + arr2) # element by element operation is performed
print('-'*50)

print(arr1 - arr2) # element by element operation is performed
print('-'*50)

print(arr1 * arr2) # element by element operation is performed
print('-'*50)

print(arr1 / arr2) # element by element operation is performed
print('-'*50)

print(arr1 // arr2) # element by element operation is performed
print('-'*50)

print(arr1 % arr2) # element by element operation is performed
print('-'*50)

print(arr1 ** arr2) # element by element operation is performed
print('-'*50)


[7 7 7 4]
--------------------------------------------------
[-3  1  5  0]
--------------------------------------------------
[10 12  6  4]
--------------------------------------------------
[0.4        1.33333333 6.         1.        ]
--------------------------------------------------
[0 1 6 1]
--------------------------------------------------
[2 1 0 0]
--------------------------------------------------
[32 64  6  4]
--------------------------------------------------


# 2.RELATIONAL OPERATOR


In [113]:
# RELATIONAL OPERATOR
print(arr1 == arr2)
print('-'*50)
print(arr1 != arr2)
print('-'*50)
print(arr1 > arr2)
print('-'*50)
print(arr1 >= arr2)
print('-'*50)
print(arr1 < arr2)
print('-'*50)
print(arr1 <= arr2)
print('-'*50)


[False False False  True]
--------------------------------------------------
[ True  True  True False]
--------------------------------------------------
[False  True  True False]
--------------------------------------------------
[False  True  True  True]
--------------------------------------------------
[ True False False False]
--------------------------------------------------
[ True False False  True]
--------------------------------------------------


# 3.BITWISE OPERATORS

In [114]:
# BITWISE OPERATORS
print(arr1 & arr2)
print('-'*50)

print(arr1 | arr2)
print('-'*50)

print(arr1 ^ arr2)
print('-'*50)

print(arr1 >> arr2)
print('-'*50)

print(arr1 << arr2)
print('-'*50)

print(~arr1)
print('-'*50)

[0 0 0 2]
--------------------------------------------------
[7 7 7 2]
--------------------------------------------------
[7 7 7 0]
--------------------------------------------------
[0 0 3 0]
--------------------------------------------------
[64 32 12  8]
--------------------------------------------------
[-3 -5 -7 -3]
--------------------------------------------------


# 4.SPECIAL OPERATORS -> in, not in, is, is not

In [115]:
# SPECIAL OPERATORS

print(2 in arr1)

print(arr2 in arr1)

print(2 not in arr1)

print(arr2 not in arr1)


True
True
False
False


In [116]:
arr3 = arr1
print(arr1)
print(arr3)
print(id(arr1),id(arr3),sep='-')
print(arr1 is arr3)

print('-'*50)


arr3 = arr1
print(arr1)
print(arr3)
print(id(arr1),id(arr3),sep='-')
print(arr1 is not arr3)

[2 4 6 2]
[2 4 6 2]
2139344753872-2139344753872
True
--------------------------------------------------
[2 4 6 2]
[2 4 6 2]
2139344753872-2139344753872
False


# 5.SHORT-HAND OPERATORS

In [117]:
# SHORT-HAND OPERATORS
print(arr1,arr2,sep='\n')
arr1 += arr2
print(arr1)

print(arr1,arr2,sep='\n')
arr1 -= arr2
print(arr1)

print(arr1,arr2,sep='\n')
arr1 *= arr2
print(arr1)







[2 4 6 2]
[5 3 1 2]
[7 7 7 4]
[7 7 7 4]
[5 3 1 2]
[2 4 6 2]
[2 4 6 2]
[5 3 1 2]
[10 12  6  4]


# **ELEMENT-WISE OPERATIONS** -> b/w arrays of different shape


# Example for scalar to one dimension

In [118]:
#example:
arr1 = np.array(3)
arr2 = np.array([2,4,5])
print(arr1, arr1.shape,arr2,arr2.shape,sep='\n')

3
()
[2 4 5]
(3,)


In [119]:
print(arr1+arr2)

[5 7 8]


# Example for scalar to two-dimenions

In [120]:
#example2:
arr1 = np.array(3)
arr2 = np.array([ [2,4] , [7,5] ])
print(arr1, arr1.shape,arr2,arr2.shape,sep='\n')

3
()
[[2 4]
 [7 5]]
(2, 2)


In [121]:
#arr1+arr2
#arr1 ----------> [ [3,3] , [3,3] ]  -> shape is (2,2)
#arr2 ----------> [ [2,4] , [7,5] ]  -> shape is (2,2)

print(arr1+arr2)


[[ 5  7]
 [10  8]]


# Example for one dimension to two dimension

In [122]:
### example 3 
arr1 = np.array([6,5])
arr2 = np.array([ [2,4] , [7,5] ])
print(arr1, arr1.shape,arr2,arr2.shape,sep='\n')

[6 5]
(2,)
[[2 4]
 [7 5]]
(2, 2)


In [123]:
#arr1+arr2
#arr2 ----------> [ [2,4] , [7,5] ]  -> shape is (2,2)
#arr1 ----------> [ [6,5] , [6,5] ]  -> shape is    (2,)
# if we check from right to left n shape 2 is matching so it gives us a solution
print(arr1+arr2)

[[ 8  9]
 [13 10]]


# Example for three-dimensions

In [124]:
arr1 = np.array([6,5,2])
arr2 = np.array([ [2,4] , [7,5] ])
print(arr1, arr1.shape,arr2,arr2.shape,sep='\n')

[6 5 2]
(3,)
[[2 4]
 [7 5]]
(2, 2)


In [125]:
#arr1+arr2
#arr2 ----------> [ [2,4,] , [7,5] ]  -> shape is (2,2)
#arr1 ----------> [ [6,5,2] , [6,5,2] ]  -> shape is (3,)

# addition is not possible because if we check above 2  and 3 is not matching
# print(arr1+arr2)

In [126]:
# example 4
arr1 = np.array([[ [2,4,5]]           , [[7,5,7] ]])
arr2 = np.array([[ [2,4,5] , [7,5,7]] , [ [1,4,5] , [8,5,2] ] ])
print(arr1, arr1.shape,arr2,arr2.shape,sep='\n')

[[[2 4 5]]

 [[7 5 7]]]
(2, 1, 3)
[[[2 4 5]
  [7 5 7]]

 [[1 4 5]
  [8 5 2]]]
(2, 2, 3)


In [127]:
#arr1+arr2
#arr2 ----------> ([[ [2,4,5],[2,4,5]]   , [[7,5,7],[7,5,7] ]])  -> shape is (2,1,3)
#arr1 ----------> ([[ [2,4,5] , [7,5,7]] , [ [1,4,5] , [8,5,2] ] ])  -> shape is (2,2,3)

# addition is not possible because if we check above 2  and 3 is not matching

print(arr1+arr2)

[[[ 4  8 10]
  [ 9  9 12]]

 [[ 8  9 12]
  [15 10  9]]]


In [128]:
# example 4
arr1 = np.array([ [2,4,5]])
arr2 = np.array([[ [2,4,5] , [7,5,7]] , [ [1,4,5] , [8,5,2] ] ])
print(arr1, arr1.shape,arr2,arr2.shape,sep='\n')

[[2 4 5]]
(1, 3)
[[[2 4 5]
  [7 5 7]]

 [[1 4 5]
  [8 5 2]]]
(2, 2, 3)


In [129]:

#arr1+arr2
#arr2 ----------> ([ [2,4,5]])                                         -> shape is (1,3)
#arr1 ----------> ([[ [2,4,5] , [7,5,7]] , [ [1,4,5] , [8,5,2] ] ])  -> shape is (2,2,3)

print(arr1+arr2)

[[[ 4  8 10]
  [ 9  9 12]]

 [[ 3  8 10]
  [10  9  7]]]


# **30-09-2026**

# Methods to create array:
1. array()

2. zeros()

3. ones()

4. full()

5. eye()

6. arange()

7. linspace()

# 2. zeros(): 

In [130]:
# 2. zeros(): 
# -> creates n-dimensional array used to create complete zeros
#zeros() is returing the array of floating numbers
a1 = np.zeros(shape=(5,))   #,dtype='int' converts float to int explicitly
print(a1)  


[0. 0. 0. 0. 0.]


# 3. ones() 

In [131]:
# 3. ones() : returs the array of floating numbers
a1 = np.ones(shape=(5,))  
print(a1) 

a1 = np.ones(shape=(5,),dtype='int')  
print(a1) 

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


# 4. full() :


In [132]:
# 4. full() :
a1 = np.full(shape=(5,),fill_value=100)
print(a1,end='\n')

a1 = np.full(shape=(2,5),fill_value=100)
print(a1)

[100 100 100 100 100]
[[100 100 100 100 100]
 [100 100 100 100 100]]


# 5. eye() 

In [133]:
#5. eye() -> uesd to create identity matrix

# N=no_of_rows , M = no_of_columns

a1 = np.eye(N=3,M=3) # this gives square matrix which means numbers_of_row = number_of_columns
print("Square Matrix")
print(a1)

print('-'*50)

a1 = np.eye(N=3,M=4) # this gives non-square matrix (numbers_of_row != number_of_columns)
print("Non-Square Matrix")
print(a1)

Square Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------------------------------
Non-Square Matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# 6. arange(start,stop,step):

In [134]:
#6. arange(start,stop,step): returns array of sequence of number from start to stop 
# start is inclusive
# stop is exclusive
np.arange(5,10,2)
# print(a1)

array([5, 7, 9])

In [135]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. linspace(start,stop) : 

In [136]:
# 7. linspace(start,stop) :  both start and stop are inclusive

np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [137]:
print(np.linspace(1,50))

len(np.linspace(1,50))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


50

In [138]:
print(np.linspace(1,25))
print('-'*50)

len(np.linspace(1,25))


np.linspace(1,25,retstep=True)


[ 1.          1.48979592  1.97959184  2.46938776  2.95918367  3.44897959
  3.93877551  4.42857143  4.91836735  5.40816327  5.89795918  6.3877551
  6.87755102  7.36734694  7.85714286  8.34693878  8.83673469  9.32653061
  9.81632653 10.30612245 10.79591837 11.28571429 11.7755102  12.26530612
 12.75510204 13.24489796 13.73469388 14.2244898  14.71428571 15.20408163
 15.69387755 16.18367347 16.67346939 17.16326531 17.65306122 18.14285714
 18.63265306 19.12244898 19.6122449  20.10204082 20.59183673 21.08163265
 21.57142857 22.06122449 22.55102041 23.04081633 23.53061224 24.02040816
 24.51020408 25.        ]
--------------------------------------------------


(array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
         3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
         5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
         8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
        10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
        13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
        15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
        18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
        20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
        23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ]),
 np.float64(0.4897959183673469))

In [139]:
np.linspace(1,10,num=5) # here 1,10 it generates 5 numbers bcz we specified num=5 which means generate 5 numbers in b/w 1 to 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# arange() -> returns array of equally spaced elements.
    -> stop is exclusive.
    -> we cannot generate the elements based on (num).
    -> we need to to specify the **step** .


# linspace() -> returns array of equally spaced elements.
    -> stop is inclusive.
    -> we can generate the elements based on (num).
    -> it calculates step using formula

# **01-10-2026**

# **Random methods to create an array**

In [140]:
import numpy.random as rd
import numpy as np

# 1. **randint()** -> generate random integers values.

In [141]:
# 1. randint()
a1 = rd.randint(10,50) 
print(a1)

print('-'*50)

a2 = rd.randint(10,50,size=(4,)) 
print(a2)
print(type(a2))

print('-'*50)

a3 = rd.randint(10,50,size=(2,3)) 
print(a3)

25
--------------------------------------------------
[11 24 18 33]
<class 'numpy.ndarray'>
--------------------------------------------------
[[18 22 44]
 [34 22 27]]


# 2. **seed()** -> to generate same set of random values/ fixs the randomness.
# we can use any number inside the seed().

In [142]:
# 2. seed() 

rd.seed(0)

# ----------------------------------------------
a1 = rd.randint(10,50) 
print(a1)

print('-'*50)

a2 = rd.randint(10,50,size=(4,)) 
print(a2)
print(type(a2))

print('-'*50)

a3 = rd.randint(10,50,size=(2,3)) 
print(a3)

10
--------------------------------------------------
[13 13 49 19]
<class 'numpy.ndarray'>
--------------------------------------------------
[[29 31 46]
 [33 16 34]]


# 3. **choice()** -> randomly it will pick the data.

# p=[] means we are deciding priority that which value should repeat or not.

# replace=False means it won't allow to generte duplicate values.

In [143]:
c1 = rd.choice(['Red','Blue','Green','White','Black','Purple'])
print(c1)

print('-'*50)

c1 = rd.choice(['Red','Blue','Green','White','Black','Purple'],size=(3,))
print(c1)

print('-'*50)

c1 = rd.choice(['Red','Blue','Green','White','Black','Purple'],size=(3,) , p=[0.2,0.3,0.05,0.05,0.4,0])
print(c1)

print('-'*50)

c1 = rd.choice(['Red','Blue','Green','White','Black','Purple'],size=(3,) , p=[0.2,0.3,0.05,0.05,0.4,0] , replace=False)
print(c1)

Red
--------------------------------------------------
['Black' 'Green' 'Blue']
--------------------------------------------------
['Black' 'Green' 'White']
--------------------------------------------------
['Black' 'Red' 'Blue']


In [144]:
rd.seed(0)

c1 = rd.choice([10,20,30,50,40,90,70,100,80],size=(3,),replace=False)
print(c1)

print('-'*50)

[100  30  20]
--------------------------------------------------


# 4. **rand()** -> we were giving the boundary
# boundary are fixed i.e; b/w 0 and 1
# in this method size,shape will not work we need to type values manually
# lower boundary is 0 , upper boundary is 1->exclusive

In [145]:
# in this method size,shape will not work we need to type values manually
a1 = rd.rand()
print(a1)
print('-'*50)

a1 = rd.rand(3)
print(a1)
print('-'*50)

a1 = rd.rand(2,3)
print(a1)


0.6458941130666561
--------------------------------------------------
[0.43758721 0.891773   0.96366276]
--------------------------------------------------
[[0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]


# 5.randn(): n-----> normal distribution
# mean is nearly equal to zero(mean ~ 0).
# standard deviation is nearly equal to one(sd ~ 1).

In [146]:
a1 = rd.randn()
print(a1)
print('-'*50)

a1 = rd.randn(3)
print(a1)
print('-'*50)

a1 = rd.randn(2,3)
print(a1)
print('-'*50)

0.48431215412066475
--------------------------------------------------
[ 0.57914048 -0.18158257  1.41020463]
--------------------------------------------------
[[-0.37447169  0.27519832 -0.96075461]
 [ 0.37692697  0.03343893  0.68056724]]
--------------------------------------------------


In [147]:
rd.seed(45)

a1 = rd.randn(2,3)
print(a1)
print('-'*50)

print("Mean: ",np.mean(a3))
print("Standard Deviation: ",np.std(a3))
print('-'*50)

[[ 0.02637477  0.2603217  -0.39514554]
 [-0.20430091 -1.27163265 -2.59687863]]
--------------------------------------------------
Mean:  31.5
Standard Deviation:  8.80814017448254
--------------------------------------------------


# **02-10-2026**

# 1. sum()

In [148]:
# one-D
a1 = np.array([2,4,3])
print(a1)
np.sum(a1)

[2 4 3]


np.int64(9)

In [149]:
# two-D
a2 = np.array([[2,4],
               [1,3]])
print(a2)
np.sum(a2)

[[2 4]
 [1 3]]


np.int64(10)

In [150]:
np.sum(a2,axis=0)  # axis = 0 means column wise sum

array([3, 7])

In [151]:
np.sum(a2,axis=1)  # axis = 1 means row wise sum


array([6, 4])

# 2.prod()

In [152]:
a2 = np.array([[2,4],
               [1,3]])
print(a2)
np.prod(a2)

[[2 4]
 [1 3]]


np.int64(24)

In [153]:
np.prod(a2,axis=0)

array([ 2, 12])

In [154]:
np.prod(a2,axis=1)


array([8, 3])

# 3.mean()

In [155]:
a2 = np.array([[2,4],
               [1,3]])
print(a2)
np.mean(a2)



[[2 4]
 [1 3]]


np.float64(2.5)

In [156]:
np.mean(a2,axis=0)

array([1.5, 3.5])

In [157]:
np.mean(a2,axis=1)

array([3., 2.])

# 4.var()

In [158]:
a2 = np.array([[2,4],
               [1,3]])
print(a2)
np.var(a2)



[[2 4]
 [1 3]]


np.float64(1.25)

In [159]:
np.mean(a2,axis=0)

array([1.5, 3.5])

In [160]:
np.mean(a2,axis=1)
        

array([3., 2.])

# 5.sqrt()

In [161]:
a2 = np.array([[2,4],
               [1,3]])
print(a2)
v = np.var(a2)

np.sqrt(v)

[[2 4]
 [1 3]]


np.float64(1.118033988749895)

# 6.std()

In [162]:
a2 = np.array([[2,4],
               [1,3]])
print(a2)
np.std(a2)



[[2 4]
 [1 3]]


np.float64(1.118033988749895)

# 7.percentile()

In [163]:
p1 = np.array([100,200,300,400,500,550,600,700,800,900,1000])
print(p1)

np.percentile(p1,50)  # middle_value is 50%

# 50% of data lies below the 550

[ 100  200  300  400  500  550  600  700  800  900 1000]


np.float64(550.0)

In [164]:


np.percentile(p1,75)  

# 75% of data lies below the 750

np.float64(750.0)

# **Array Manipulation Methods**

# **1.reshape()** -> To change shape of an array

In [165]:
a1 = np.arange(10,22)
print(a1,a1.size)


[10 11 12 13 14 15 16 17 18 19 20 21] 12


## Factors of 12 -> here 12 is length of array

## (1,12), (2,6), (3,4), (4,3), (6,2), (12,1)

## (2,2,3),(3,2,2),(1,12,1)

# (2,6,1),(1,6,2),(6,2,1)

In [166]:
np.reshape(a1,shape=(2,6))


array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [167]:
a1 = np.array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

print(a1)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]]


## shape = -1 will convert any dimesions into only one-dimesion array

In [168]:
np.reshape(a1,shape=-1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [169]:
np.reshape(a1,shape=(2,6,1))


array([[[10],
        [11],
        [12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19],
        [20],
        [21]]])

# 2. ravel()  -> converts multi-dimensional array to one-D

In [170]:
np.ravel(a1)  # here np.



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

# 3. flatten() -> converts multi-dimensional array to one-D

In [171]:
a1.flatten()  # here a1.


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

# **03-10-2026**

# copy() and view() methods

## **copy()** ->  returns the shallow copy of the given array. means both the arrays are independent of each other

In [172]:
a1 = np.array([10,20,30])
print(a1)
print('-'*50)


a2 = np.copy(a1)
print(a2)
print('-'*50)


a1[0] = 100
print(a1,a2,sep='\n')

[10 20 30]
--------------------------------------------------
[10 20 30]
--------------------------------------------------
[100  20  30]
[10 20 30]


## view() -> a1 and a2 are dependent on each other

In [173]:
a1 = np.array([10,20,30])
print(a1)
print('-'*50)

a2 = a1.view()
print(a2)
print('-'*50)

a1[0] = 100
print(a1,a2,sep='\n')

[10 20 30]
--------------------------------------------------
[10 20 30]
--------------------------------------------------
[100  20  30]
[100  20  30]


## here reshape() -> here it returns copy

In [174]:
a1 = np.arange(10,22)
print(a1,a1.size)
print('-'*50)

res = np.reshape(a1,shape=(2,6))
print(res)
print('-'*50)

a1[0] = 100
print(a1,res,sep='\n')



[10 11 12 13 14 15 16 17 18 19 20 21] 12
--------------------------------------------------
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]]
--------------------------------------------------
[100  11  12  13  14  15  16  17  18  19  20  21]
[[100  11  12  13  14  15]
 [ 16  17  18  19  20  21]]


## ravel() -> it returns view

In [175]:
a1 = np.arange(10,22)
print(a1,a1.size)
print('-'*50)

res = np.ravel(a1)
print(res)
print('-'*50)

a1[0] = 100
print(a1,res,sep='\n')



[10 11 12 13 14 15 16 17 18 19 20 21] 12
--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19 20 21]
--------------------------------------------------
[100  11  12  13  14  15  16  17  18  19  20  21]
[100  11  12  13  14  15  16  17  18  19  20  21]


## here flatten() -> here it returns copy

In [176]:
a1 = np.arange(10,22)
print(a1,a1.size)
print('-'*50)

res = a1.flatten()
print(res)
print('-'*50)

a1[0] = 100
print(a1,res,sep='\n')



[10 11 12 13 14 15 16 17 18 19 20 21] 12
--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19 20 21]
--------------------------------------------------
[100  11  12  13  14  15  16  17  18  19  20  21]
[10 11 12 13 14 15 16 17 18 19 20 21]
