# **05-10-2026**

# **Slicing**

In [1]:
import numpy as np

In [ ]:
a1 = np.arange(10,30)

print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [ ]:
a1[::-1] # reversing the array

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [6]:
a1[::2] # alterante elements

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
#output: [11,13,15]
a1[1:6:2]

array([11, 13, 15])

In [12]:
a1.size


20

# Factors of 20 ->
# (2,10), (4,5), (5,4), (10,20)

In [13]:
a2 = np.reshape(a1,(4,5))
print(a2)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [21]:
a2[::2]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [22]:
a2[::2 , ::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [30]:
a2[::-2,::-3]

array([[29, 26],
       [19, 16]])

In [32]:
a2[::2,::4]

array([[10, 14],
       [20, 24]])

In [47]:
a2 = np.reshape(a1,(4,5))
print(a2)

a2[-2::-2,::-1]
#   a2[2::-2,::-1]  

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([[24, 23, 22, 21, 20],
       [14, 13, 12, 11, 10]])

In [52]:
a3 = np.array( [ [ [10, 11, 12, 13, 14] , [15, 16, 17, 18, 19] ],
                 [ [20, 21, 22, 23, 24] , [25, 26, 27, 28, 29] ]  
               ])
print(a3)

[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [56]:
print(a3[0,0,2])

12


In [61]:
print(a3[1,1,4])

print(a3[-1,-1,-1])

29
29


In [62]:
print(a3[1,0,3])

23


In [ ]:
a3[::] 

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [66]:
a3[0,0,0]

np.int64(10)

In [70]:
a3[::,::,0]

array([[10, 15],
       [20, 25]])

In [71]:
a3[::,::,-2]

array([[13, 18],
       [23, 28]])

In [76]:
a3[::,::,::2]

array([[[10, 12, 14],
        [15, 17, 19]],

       [[20, 22, 24],
        [25, 27, 29]]])

In [80]:
a3[::-1,::-1,-1]

array([[29, 24],
       [19, 14]])

In [81]:
a3[::] 

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [89]:
a3[::-1,1,-1]

array([29, 19])